version: '2'
services:
  database:
    image: mariadb:10.2.10
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myawesomeuser
      MYSQL_PASSWORD: mysecretpassword
    volumes:
       - ./mysql:/var/lib/mysql
    restart: always
  web:
    # require: database
    image: myflaskapp
    container_name: myawesomecontainer
    depends_on:
      - "database"
    volumes:
      - ./app:/app
    ports:
      - "8092:80"
    environment:
      - FLASK_APP=main/main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"